export const STARTER_FOODS = [
  {
    id: "starter:banana",
    name: "Banana",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:banana",
    confidence: "manual",
    servingGrams: 118,
    ingredients: "Banana",
    per100: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3, fiber: 2.6 },
  },
  {
    id: "starter:apple",
    name: "Apple",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:apple",
    confidence: "manual",
    servingGrams: 182,
    ingredients: "Apple",
    per100: { calories: 52, protein: 0.3, carbs: 13.8, fat: 0.2, fiber: 2.4 },
  },
  {
    id: "starter:egg",
    name: "Egg",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:egg",
    confidence: "manual",
    servingGrams: 50,
    ingredients: "Egg",
    per100: { calories: 143, protein: 12.6, carbs: 0.7, fat: 9.5, fiber: 0 },
  },
  {
    id: "starter:rice-cooked",
    name: "Rice, cooked",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:rice-cooked",
    confidence: "manual",
    servingGrams: 150,
    ingredients: "Cooked white rice",
    per100: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3, fiber: 0.4 },
  },
  {
    id: "starter:chicken-breast",
    name: "Chicken breast, cooked",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:chicken-breast",
    confidence: "manual",
    servingGrams: 100,
    ingredients: "Cooked skinless chicken breast",
    per100: { calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0 },
  },
  {
    id: "starter:yogurt",
    name: "Plain yogurt",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:yogurt",
    confidence: "manual",
    servingGrams: 170,
    ingredients: "Plain yogurt",
    per100: { calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0 },
  },
  {
    id: "starter:milk",
    name: "Milk",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:milk",
    confidence: "manual",
    servingGrams: 244,
    ingredients: "Milk",
    per100: { calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0 },
  },
  {
    id: "starter:oats",
    name: "Oats",
    brand: "Common food",
    source: "Starter food",
    sourceId: "starter:oats",
    confidence: "manual",
    servingGrams: 40,
    ingredients: "Rolled oats",
    per100: { calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9, fiber: 10.6 },
  },
  {
    id: "starter:nasi-lemak",
    name: "Nasi lemak",
    brand: "Starter estimate",
    source: "Starter food",
    sourceId: "starter:nasi-lemak",
    confidence: "manual",
    servingGrams: 350,
    ingredients: "Coconut rice, sambal, egg, peanuts, anchovies, cucumber",
    per100: { calories: 189, protein: 6, carbs: 24, fat: 8, fiber: 1.5 },
  },
  {
    id: "starter:roti-canai",
    name: "Roti canai",
    brand: "Starter estimate",
    source: "Starter food",
    sourceId: "starter:roti-canai",
    confidence: "manual",
    servingGrams: 95,
    ingredients: "Flatbread made with flour, fat, and water",
    per100: { calories: 320, protein: 7, carbs: 46, fat: 12, fiber: 2 },
  },
];
